version: "3.0"
services:
  postgres:
    image: postgres
    network_mode: host
    env_file:
      - .env

  frontend:
    image: cctv_frontend
    build: .
    network_mode: host
    env_file:
      - .env
    depends_on:
      - postgres